[package]
name = "pingora-bench"
version = "0.1.0"
edition = "2021"
[dependencies]
pingora = { version = "0.6.0", features = ["lb"] }
async-trait = "0.1"
tokio = { version = "1", features = ["full"] }
